### ISSUE TITLE
No lisence statement

### ISSUE THREAD

**Issue by kraiv** [namshi/AB#9]
Hi,
I would like to use this nice code in our company, but I confuse because there is no license statement.
Can I use this code for commercial purpose?
We are not going to re-distribute, just only use and customize the code.

**Comment by odino** [comment]
Hey @kraiv 

this project is released under the [MIT license](https://github.com/namshi/AB/blob/master/composer.json#L7), so feel free to use it for commercial purposes! Enjoy!

**Comment by kraiv** [comment]
thanks a lot!!
